version: "3"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=${MM_USERNAME}
      - POSTGRES_PASSWORD=${MM_PASSWORD}
      - POSTGRES_DB=${MM_DBNAME}
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      args:
        # - edition=team
        - PUID=1000
        - PGID=1000
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/app/mattermost/config:/mattermost/config:rw
      - ${DATA_PATH_HOST}/app/mattermost/data:/mattermost/data:rw
      - ${DATA_PATH_HOST}/app/mattermost/logs:/mattermost/logs:rw
      - ${DATA_PATH_HOST}/app/mattermost/plugins:/mattermost/plugins:rw
      - ${DATA_PATH_HOST}/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=${MM_USERNAME}
      - MM_PASSWORD=${MM_PASSWORD}
      - MM_DBNAME=${MM_DBNAME}

      # use the credentials you've set above, in the format:
      - MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
      #- MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ${DATA_PATH_HOST}/web/cert:/cert
      - /etc/localtime:/etc/localtime:ro
